# NumPy
Librería de ampliación del módulo básico de Python

In [1]:
#Lo primero que hay que hacer es importar la librería
#Pero como el nombre numpy tiene 5 letras podemos utilizar un acrónimo para acortarlo
#Con el acrónimo ya no tenemos que poner "numpy" cada vez que utilicemos alguna función
import numpy as np #LA MEJOR OPCIÓN (RECOMENDACIÓN PROFE)

In [3]:
#De esta forma no tenemos que anteponer ningún prefijo a las funciones de numpy
#Podemos escribir las funciones sin el prefiijo
#Aun así no es recomdable porque puede ser que el nombre de las funciones
#coincida con otras librerías, haciendo que el intérprete de Python nos obligue a poner el nombre de la lirería
from numpy import * #NO RECOMENDADO

In [10]:
L1 = [1,2,3,4,5,6,7,8] # Crear una lista

In [14]:
x1= np.array(L1) #Convertir a array los objetos de la lista
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
x2= np.array(L1, dtype = 'float32') #Convertir a array y especificar el tipo de dato que contiene
x2                                    #En este caso el dato es de tipo decimal

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

### Tipos de datos
- bool_ (booleanos)
- int_, intc, intp, int8, int16, int32, int64 (números enteros)
- uint8, uint16, uint32, uint64 (enteros sin signo)
- float_, float16 (+/-9999999999e99999), float32, float64 (que es igual a float_)
- complex_, complex64, complex128 (a+bi, a,b $\in$ float_)


In [17]:
np.zeros((3,4)) #Creación de matriz de ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((4,3)) #Creación de matriz de unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.arange(10) #Creación de array de 10 números de forma incremental

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(3,12,dtype=np.float) #Array con números entre 3 y 12 y de tipo punto flotante (decimales)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [22]:
np.arange(4,5,0.1) #Array con números entre 4 y 5, de 0.1 en 0.1

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [24]:
#Función para crear un array con el nº especificado de elementos separado de forma equivalente entre el valor de inicio y el valor de fin
np.linspace(1., 7., 12) 

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [25]:
#Matriz identidad de 5 por 5 (con 1 en la diagonal)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
x = np.zeros((8,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
#Para cambiar la forma del array, redistribuir los mismos elementos de forma distinta
x.reshape((6,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
x3 = np.arange(24)
x3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
x3.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
x3.reshape((3,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [42]:
#Función que devuelve EL MISMO ARRAY (no copia) pero de forma unidimensional
#"Aplana" un array y lo deja en una sola fila
x = np.array([[1,2,3,4], [5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
#flatten es una función que devuelve una copia del array colapsado
#en una dimensión. Devuelve una COPIA colapsada en una dimensión.
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
#Transposición del array (cambiar filas por columnas)
x= np.transpose(x)
x

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [11]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
np.resize(x, (5,3)) #Como en R, si se ponen más filas que elementos, se acaban repitiendo elementos del array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

### Ejercicios propuestos
1. Crear un array de datos con valores entre 5 y 120.
2. Crear una matriz 4x4 con los valores desde 0 hasta 15.
3. Crear la identidad 7x7.
4. Crear un array de 20 elementos y transformarlos en una matriz 5x4.
5. Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme. 

In [16]:
#Ejercicio 1
Datos = np.arange(5,121)
Datos

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

In [18]:
#Ejercicio 2
matriz = np.arange(0,16)
matriz

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
matriz4x4 = np.resize(matriz,(4,4))
matriz4x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
#Ejercicio 3
Identidad = np.eye(7)
Identidad

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [24]:
#Ejercicio 4
elementos = np.arange(20)
elementos

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
matriz5x4 = np.resize(elementos,(5,4))
matriz5x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [28]:
#Ejercicio 5
equidistante = np.linspace(0, 5, 20)
equidistante

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

## Propiedades de los arrays
Cosas que le podemos preguntar al array, cosas inherentes al mismo, tamaño, dimensión, tipo de datos, etc.

In [5]:
x = np.arange(12)
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
#En Python el número de dimensiones se le llama rango
#Dos dimensiones: filas y columnas
x.ndim

2

In [7]:
#Tupla que indica el tamaño de la matriz en cada una de las dimensiones
#Tamaño (n,m): 3 filas y 4 columnas
x.shape

(3, 4)

In [8]:
#Número total de elementos que tiene la matriz
#Es igual al producto de nxm (3x4)
x.size

12

In [9]:
#Tipo de dato que contiene la matriz
#Número entero de 32 bits
x.dtype

dtype('int32')

In [11]:
#Tamaño en bits de cada uno de los elementos de la matriz
#Cada número lo que ocupa en bits
x.itemsize

4

In [12]:
#Posición en la memoria RAM del ordenador
#Normalmente no es necesario hacer esto porque no es necesario pasar por la posición de memoria
x.data

In [13]:
#Acceder a elementos. Cómo acceder a la fila número 2.
#Recordar que hay fila 0, 1 y 2. Empieza por 0.
x[2]


array([ 8,  9, 10, 11])

In [14]:
#Acceder a fila 2, columna 1. Nos da el elemento concreto.
x[2,1]

9

In [16]:
#Modificar atributos. Cambiar la forma del array.
#En vez de 3x4 ahora queremos que sea 4x3
x.shape = (4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
#Acceder a las filas de la 1 a la 2, y a las columnas de la 0 a la 1
#Recordar que el último número que ponemos no se incluye
x[1:3, 0:2]

array([[3, 4],
       [6, 7]])

In [21]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
#Acceder a los elementos del 3 al 7
y[3:8]

array([3, 4, 5, 6, 7])

In [25]:
#Acceder a los elementos del 1 al 6, de 2 en 2
y[1:7:2]

array([1, 3, 5])

In [26]:
#Uso de un array para indexar otro array
#array del 10 al 7 en saltos de -1
z = np.arange(10,6,-1)
z

array([10,  9,  8,  7])

In [27]:
#Devuelve los elementos de z que están en y
y[z]

array([10,  9,  8,  7])

In [28]:
#Acceder por condición booleana en vez de por posición
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [29]:
#Si nos queremos quedar con los números más grandes que 30
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [31]:
#Generar un vector lógico. CONDICIÓN BOOLEANA (cond)
cond = x < 25
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [32]:
#Acceder a los elementos que cumplan dicha condición booleana
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
#Asignación de un mismo valor a un conjunto de elementos del array
x[12:24] = 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [36]:
#Asignación de un conjunto de valores a un conjunto de elementos del array con la misma longitud
x[13:16] = [6,9,12]
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [37]:
x.dtype #Número entero de 32 bits

dtype('int32')

In [39]:
#Como el array solo tiene números enteros, si intentamos asignar a un elemento un número decimal
#Nos devuelve el número entero redondeado y no el decimal, porque tiene que haber homogeneidad
#En este caso como el tipo de dato es un número entero, el número pi te lo coloca como 3
x[5]= 3.1415
x

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [40]:
#Intento de asignación de número complejo en el array
#ERROR: No puede convertir el número complejo a entero
x[8]= 1.2j

TypeError: can't convert complex to int

## Copias y vistas de arrays
Una de las confusiones más típicas es saber cuando estamos utilizando el array original o cuando se está creando una copia del mismo para no machacar los datos. 

In [44]:
#PRIMER CASO: CUANDO HACEMOS UNA ASIGNACIÓN
x = np.arange(10)

In [45]:
#Creamos una variable que referencia al primer array creado.
#No creamos una copia sino una referencia
#El cambio de uno se verá reflejado en el otro
#La asignación comparte información y propiedades
y = x

In [47]:
#Cambiamos y
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
#Cambia x también (porque y no es una copia de x)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
#SEGUNDO CASO: HACEMOS UNA COPIA
#¿Qué podemos hacer? Una copia del array
#La copia comparte información pero no propiedades
z = x.copy()
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [50]:
z is x #es una copia no es x

False

In [51]:
y is x #es una referencia de x, son lo mismo

True

In [52]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
#TERCER CASO: CREACIÓN DE UNA VISTA
#Es una vista diferente del mismo array, del mismo objeto, pero visto de otra manera
#Las VISTAS son partes del conjunto global, comparten la información pero con propiedades diferentes
#La vista comparte información, no comparte propiedades, pero si se modifica también se modifica el array original
t = x.view()
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
t.shape = (5,2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
#Seleccionar una parte de un array es una VISTA
s = x[0:2, 1:3]
s

array([[1, 2],
       [6, 7]])

In [60]:
#Seleccionar todos los elementos del array y asignarle un número
s[:] = 5
s

array([[5, 5],
       [5, 5]])

In [61]:
#Al modificar la VISTA también se ha modificado el array original x
x

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

# Funciones Universales de Numpy (ufunc)

Funciones que realizan operaciones sobre todos los elementos de un array sin tener que implementar un bucle para recorrer el array elemento a elemento.

- Unarias: sqrt, sin, cos, **2
- Binarias (reciben 2 arrays y devuelven 1 como resultado): maximum, minimum

In [62]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
#Operaciones aritméticas (sumar,restar, multiplicar, dividir)= unarias
#Sumar
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [64]:
#Restar
x-3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [65]:
#Multiplicar
x*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [66]:
#Dividir
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [68]:
# 4 Ángulos generados entre 0 y 2pi
alpha = np.linspace(0,2*np.pi,4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [69]:
#Seno de alpha
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [70]:
#Coseno de alpha
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [71]:
#Tangente de alpha
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [72]:
#Exponenciales y logaritmos
#Para elevar e a cada uno de los elementos del vector x (e elevado a 0, e elevado a 1, etc.)
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [73]:
#Para elevar 2 a cada uno de los elementos del vector (2 elevado a 0, 2 elevado a 1, etc.)
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [74]:
#Potencias
#Para elevar 3 a x( 3 elevado a 0, 3 elevado a 1, etc.)
np.power(3,x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683], dtype=int32)

In [75]:
#x elevado a 2, al cuadrado (0 elevado a 2, 1 elevado a 2, etc.)
np.power(x,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [76]:
#Logaritmos
#Aviso de que log 0 es igual a -infinito. No existe. Llevar cuidado.
#Creo que es el logaritmo neperiano
np.log(x)

C:\Users\cr_sa\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [77]:
#Logaritmo en base 2
#De nuevo sale el aviso de -infinito
np.log2(x)

C:\Users\cr_sa\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log2
  


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [78]:
#Logaritmo en base 10
np.log10(x)

C:\Users\cr_sa\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

$$\sum_{i=1}^n x_i$$

In [79]:
#DATOS ESTADÍSTICOS 
#Dos vertientes: la función que toma todos los datos y la que hace la operación eliminando los NaN que puedan haber
np.sum(x)

45

In [80]:
np.nansum(x)

45

In [81]:
np.prod(x) #El producto de los elementos de x (como hay un 0 el resultado es 0)

0

In [82]:
np.mean(x) #La media

4.5

In [83]:
np.median(x) #La mediana

4.5

In [84]:
np.min(x) #El valor más pequeño

0

In [85]:
np.max(x) #El valor más grande

9

In [86]:
np.std(x) #Desviación típica

2.8722813232690143

In [88]:
np.var(x) #La varianza, que es el cuadrado de la desviación típica

8.25

In [89]:
#Posición/índice en la cual se encuentra el valor más pequeño
#Coincide con el valor porque coinciden posición y valor
np.argmin(x)

0

In [90]:
#Posición en la que se encuentra el valor más grande
np.argmax(x)

9

In [91]:
#Para calcular los percentiles (especificar el quantil exacto que queremos calcular)
np.percentile(x, q=0.95)

0.08549999999999999

In [94]:
y = np.array([True, False, True])

In [95]:
#Si alguno de los elementos tiene True,esta función devuelve True
np.any(y)

True

In [96]:
#Si todos los elementos son True, esta función devuelve True
np.all(y)

False

In [104]:
#Para sumar,restar, etc., por filas o por columnas
#Primero generamos una matriz 3x5 con valores aleatorios entre 0 y 1
np.random.seed(2019) #Semilla a partir de la cual se generan todos los números aleatorios
z = np.random.random((3,5)) #Con la semilla da siempre los mismos resultados a pesar de tener valores aleatorios
z

array([[0.90348221, 0.39308051, 0.62396996, 0.6378774 , 0.88049907],
       [0.29917202, 0.70219827, 0.90320616, 0.88138193, 0.4057498 ],
       [0.45244662, 0.26707032, 0.16286487, 0.8892147 , 0.14847623]])

In [105]:
z.sum() #Suma de todos los valores dentro de la variable z

8.550690063213514

In [106]:
#SUMA POR COLUMNAS
z.sum(axis = 0) #da como resultado 5 valores por las 5 columnas

array([1.65510085, 1.3623491 , 1.69004099, 2.40847402, 1.43472509])

In [107]:
#SUMA POR FILAS
z.sum(axis=1) #Tres resultados por las tres filas

array([3.43890915, 3.19170818, 1.92007274])

In [ ]:
#Si generamos una matriz en vez de ser cuadrada es cubo
#Es decir una matriz con filas, columnasy profundidad
#Podemos también calcular en base a la profundidad