# Tema 1 - Matrices
Vamos a ver cómo crear una matriz utilizando la librería **numpy**.

In [2]:
#Declarar una fila
row = [1,2,3]
row

[1, 2, 3]

In [3]:
#Declarar una columna
col = [[1],[2],[3]]
col

[[1], [2], [3]]

In [4]:
#Crear una matriz
M = [[1,2,3],[4,5,6],[7,8,9]]
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
M[1][1] #Acceder al elemento de la fila 1 y columna 1 

5

In [6]:
M[0][0] #Acceder al elemento de la primera fila y de la primera columna

1

In [39]:
M[0] #Acceder a la primera fila

array([1., 2., 3.])

In [40]:
#Acceder a la primera columna (hay que hacer un bucle)
for row in M:
    print(row[0])
 

1.0
4.0
7.0


In [9]:
import numpy as np

In [11]:
#Creación de una matriz con numpy
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype= complex)
M

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [15]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [16]:
#Matriz de ceros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#Matriz de unos
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
#Para saber el número de filas y columnas de una matriz
np.shape(M)

(3, 3)

In [23]:
#Operaciones matriciales
A = np.array([[1,2],[3,4]])
print(A)
B = np.array([[3,0],[1,-1]])
print(B)

[[1 2]
 [3 4]]
[[ 3  0]
 [ 1 -1]]


In [20]:
A+B #Suma

array([[4, 2],
       [4, 3]])

In [22]:
A.dot(B) #Producto matricial (en R sería A%*%B)

array([[ 5, -2],
       [13, -4]])

In [24]:
A.transpose() #Transpuesta de la matriz

array([[1, 3],
       [2, 4]])

In [25]:
A.trace() #Traza: la suma de los elementos de la diagonal de la matriz

5

In [27]:
#np.linalg. -->paquete de álgebra lineal 
np.linalg.matrix_rank(A) #rango de la matriz, si es menor que el tamaño de la matriz no es invertible, en este caso sí lo es

2

In [28]:
#Matriz elevado a un número (potencia)
np.linalg.matrix_power(A,5) #A elevado a 5

array([[1069, 1558],
       [2337, 3406]])

In [29]:
#Determinante de una matriz
np.linalg.det(A) #matriz invertible

-2.0000000000000004

In [30]:
#Para hacer la inversa de una matriz
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [31]:
#Matriz IDENTIDAD
np.linalg.inv(A).dot(A) #No parece la identidad por los decimales pero se aproximan a cero los que no están en la diagonal

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [33]:
#Creación de matriz no invertible
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.linalg.det(x) #El determinante da prácticamente 0, no invertible

-9.51619735392994e-16

In [35]:
np.linalg.matrix_rank(x) #Rango menor que el tamaño de la matrix --> no invertible

2

In [36]:
np.linalg.inv(x) #Te hace la inversa de aquella manera, con números que son prácticamente infinito 

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

No se nos ocurrirá NUNCA hacer la inversa ni de una matriz cuadrada, ni de una matriz cuyo rango sea inferior a su orden (el número de filas/columnas de la misma).

In [38]:
#Una matriz que no es cuadrada (mismo nº filas y columnas) no es invertible, va a dar ERROR
#np.linalg.inv(np.array([[1,2,3],[4,5,6]]))

LinAlgError: Last 2 dimensions of the array must be square